### ISSUE TITLE
Support type and attribute selectors with namespace prefix

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/pipeline-mod-braille#11]
Example:

``` css
[epub|type="..."] {
  ...
}
```

See
- http://www.w3.org/TR/css3-namespace
- http://www.w3.org/TR/css3-selectors/#typenmsp
- http://www.w3.org/TR/css3-selectors/#attrnmsp

**Comment by bertfrees** [comment]
Another use case is `[xml|space=preserve] { ... }`, see https://github.com/snaekobbi/sprints/issues/117 and https://github.com/daisy/pipeline-mod-braille/issues/53.

**Comment by bertfrees** [comment]
Another use case is `[brl|class=foo] { ... }`. Question: should it be possible to match this with `.foo` instead?

**Comment by bertfrees** [comment]
> Question: should it be possible to match this with `.foo` instead?

The answer is no, see http://www.w3.org/TR/css3-selectors/#attrnmsp: `[attr]` == `[|attr]`

**Comment by bertfrees** [comment]
See commits https://github.com/snaekobbi/jStyleParser/compare/68564274a72d31416f360de7217e52313ce543d0...7c587629f5b70f61a46df121aeff5ff3d2ce783c

**Comment by dkager** [comment]
Awesome! And I just realized it uses ANTLR which I had been meaning to have a brief look at anyway.
I will happily test my use case (xml|space) whenever you want.
