### ISSUE TITLE
Support double-sided printing

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/pipeline-mod-braille#27]
Depends on:
- [x] https://github.com/snaekobbi/braille-css-spec/issues/19

**Comment by bertfrees** [comment]
@jukkae This could be another topic for you to explore. What needs to be done in the various parts (CSS, OBFL, PEF, liblouis, dotify, pipeline-mod-braille) to support double-sided printing and make an overview here.

**Comment by bertfrees** [comment]
This works. I did not have to do anything special, because OBFL/Dotify already supported single- and double-sided printing. Currently I simply assume we're always printing double-sided (https://github.com/daisy/pipeline-mod-braille/commit/0b179a5bcd65d413e50ced3738283633b0834e5d), as is the case in CSS (https://github.com/snaekobbi/braille-css-spec/commit/7e863c33908109f5a517a8fd98de785a91b9c503), so I didn't even have to add a single-/double-sided switch. Printing single-sided is currently achieved by modifying the PEF (change "duplex='true'" to "duplex='false'"). However it turns out people do see the benefit of having such a switch.
- [ ] To do: add single-/double-sided switch to scripts.

Note that I have assumed switching from double-sided to single-sided within a document is not a requirement. If this is a requirement, a change will have to be made to the CSS spec.

**Comment by dkager** [comment]
So you'd make the switch work on the PEF level, not by something in OBFL or a parameter for Dotify?
Does anyone need to set this through a meta field in the book? E.g. books for young children or beginner braille users may always need to be printed single-sided as per the product specifications. At first glance this extra flexibility looked useful to me but on further thought I think this belongs in a template.

**Comment by bertfrees** [comment]
Yes I think it would be a parameter for Dotify.

**Comment by bertfrees** [comment]
It will probably be a script option (useful for everybody, can be put in template) which could be overwritten by a meta field in a book if needed (useful for Dedicon).

**Comment by bertfrees** [comment]
Fixed by https://github.com/daisy/pipeline-mod-braille/commit/723ae48157c31f546e6529ef4ca3339a689029d2.
