### ISSUE TITLE
Support Swedish braille code

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/pipeline-mod-braille#42]
To do:
- [x] Integrate Swedish <del>liblouis table or</del> Dotify translator
- [x] Higher level translator component

Depends on:
- [ ] ~~https://github.com/snaekobbi/liblouis/issues/3~~
- [x] https://github.com/snaekobbi/issues/issues/14

**Comment by bertfrees** [comment]
Higher level translator component: see https://github.com/snaekobbi/pipeline-mod-mtm/commit/e34a62d43c83924e79d8c3d9e4ee5619502adba6.

The Swedish Dotify translator is used for pre-translation. 

Inline formatting is currently not supported, but it could be if I make use of the `translate(String text, TextAttribute attributes)` method of `BrailleTranslator`. (Pre-)hyphenation is currently not supported because of the way line breaking is done in Dotify.

Alternatively, if we don't want pre-translation we should be able to accomplish that with a custom `CSSStyledDocumentTransform` and some adjustments to `dotify:format`.

**Comment by joeha480** [comment]
I prefer not using pre-translation if possible, because then I can add support for non-standard hyphenation and also line breaking aware translation

**Comment by bertfrees** [comment]
See https://github.com/snaekobbi/pipeline-mod-braille/issues/51

**Comment by bertfrees** [comment]
This can be closed.

The pre-translation path now supports hyphenation (https://github.com/daisy/pipeline-mod-braille/issues/44). It does still not support text-level formatting, but I guess that is OK for now. When we need it (e.g. for e-braille or for the edit format) we'll create a new issue.

The translation-while-formatting path is now also supported (https://github.com/snaekobbi/pipeline-mod-braille/issues/51).
