### ISSUE TITLE
DTBook to PEF script

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/pipeline-mod-braille#45]
We have several options:
1. Currently dtbook-to-pef uses dtbook-to-zedai and zedai-to-pef.
2. We can use [nordic-epub3-dtbook-migrator](https://github.com/nlbdev/nordic-epub3-dtbook-migrator) and [epub3-to-pef](https://github.com/snaekobbi/pipeline-mod-braille/issues/43)
3. A direct conversion.
4. No script. The reasoning is that if the conversion is just a wrapper around a dtbook-to-epub3 step and an epub3-to-pef step (option 2), users might as well run them in sequence manually.

@josteinaj and @bertfrees are more in favour of the direct conversion. Option 2 gives us the limitation that the input must be a valid Nordic DTBook which is a very limiting grammar. If all agencies are using the Nordic DTBook standard this limitation is not a problem.

The direct conversion gives us some extra work, notably:
- CSS needs to be written for both input formats (both default style sheets and style sheets in templates).
- Input format aware translation components need to written for both input formats.
- Some special pre-processing steps (e.g. generating special content) need to be written for both input formats.

Also, users have to realize that converting a Nordic EPUB will not necessarily give them the same result as when they convert the equivalent Nordic DTBook.

**Comment by josteinaj** [comment]
blocked on: daisy/pipeline-mod-braille#30

**Comment by bertfrees** [comment]
@stesk Which version of DTBook did you say Nota uses today? 1.1.0 (http://www.daisy.org/z3986/specifications/Z39-86-2002.html#DTBookDTD)? I don't think we need to take a lot of special precautions, maybe an extra CSS file (it depends on the compatibility between the DTBook versions). But I want to make it clear in the requirements anyway.

**Comment by stesk** [comment]
@bertfrees Yes, that's the one.

**Comment by bertfrees** [comment]
Fixed by commit https://github.com/daisy/pipeline-mod-braille/commit/7d9ce376c174be2a212372c82852a455a5e3136b (option 3: direct conversion). DTBook 1.1.0 is not addressed yet.

**Comment by bertfrees** [comment]
For DTBook 1.1.0: see https://github.com/snaekobbi/pipeline-mod-braille/issues/62. Closing this one.
