### ISSUE TITLE
Support translation while formatting in dotify:format

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/pipeline-mod-braille#51]
We could either have `obfl:style` elements with name `text-transform:none` for all text that is pre-translated, or we could just translate all text that is not Unicode braille yet.

**Comment by joeha480** [comment]
Is there a downside to just translate?

**Comment by bertfrees** [comment]
Don't know. Possibly you get unexpected results, i.e. if Unicode braille is not translated to Unicode braille or if something happens with white space or hypenation marks. I just want to make sure "pre-translated" is indeed "pre-translated" and not "translated twice".

**Comment by bertfrees** [comment]
See https://github.com/daisy/pipeline-mod-braille/commit/a37d7daf247975776b3b969b1f1c5ed76a61309a. Of most interest to you @joeha480  is probably the file [BrailleTranslatorFactoryServiceImpl.java](https://github.com/daisy/pipeline-mod-braille/blob/a37d7daf247975776b3b969b1f1c5ed76a61309a/pipeline-braille-utils/dotify-utils/dotify-formatter/src/main/java/org/daisy/pipeline/braille/dotify/impl/BrailleTranslatorFactoryServiceImpl.java).
