### ISSUE TITLE
Can't install liblouis-utils/liblouis-core to the Maven repository

### ISSUE THREAD

**Issue by dkager** [snaekobbi/pipeline-mod-braille#58]
`cd pipeline-braille-utils/liblouis-utils && mvn install`

Error:

```
[ERROR] Bundle org.daisy.pipeline.modules.braille:liblouis-core:bundle:3.1.3 : In component null, multiple references with the same name: LiblouisTablePath. Previous def: org.daisy.pipeline.braille.liblouis.LiblouisTablePath, this def:
[ERROR] Error(s) found in bundle configuration
```

First guess: there are differences in `OSGI-INF/liblouis-native-<platform>.xml` that cause issues.

**Comment by bertfrees** [comment]
Got the same error after updating to Java 8.

**Comment by bertfrees** [comment]
Same problem in texhyph-core. But not in libhyphen-core because it doesn't use the annotations. The libhyphen-core tests pass which suggests this is more a BND problem than a Java problem.

**Comment by bertfrees** [comment]
If this one error is the only problem of switching to Java 8, and it can be solved by removing the annotations and manually creating the SCR file again, that's an option, but I don't want to move to manual SCR files again for the whole project.

We can also just say in the build instructions that JDK8 is not allowed.

I don't exclude that there's a bug in my code, but I have no clue what that would be, and the BND error isn't very helpful.

**Comment by dkager** [comment]
The only other issue I’ve had is with Javadoc doclint, but considering our goal of maintainability fixing those errors and warnings is actually a good idea I think.
Good to know it’s Java 8, this at least narrows the scope of the issue somewhat.

**Comment by bertfrees** [comment]
If it's a BND bug all we can do really is avoid the error by removing the annotations. If it's a bug in my code it basically comes down to the same thing. As said above it's an acceptable solution as long as it's just these one or two classes. Will you have a look or should I? We have to verify that all the modules build with Java 8.

**Comment by dkager** [comment]
Since I have Java 8 I can have a look but that’ll be on Monday. So if you find time before then that’d be appreciated. :)
