### ISSUE TITLE
Make liblouis-utils/liblouis-mathml build on Windows

### ISSUE THREAD

**Issue by dkager** [snaekobbi/pipeline-mod-braille#59]
Update pipeline-braille-utils/liblouis-utils/liblouis-mathml/pom.xml:
- [x] Have the checkout and the script in an optional profile.
- [x] daisy#28

**Comment by bertfrees** [comment]
Related: https://github.com/daisy/pipeline-mod-braille/issues/28

**Comment by bertfrees** [comment]
- Either we could convert the bash script into Java, or more simple, 
- we can make the bash script external (not part of the Maven build) and add the files that are checked out to the source.

Don't like so much your idea of having two counterparts.

**Comment by bertfrees** [comment]
Or rather have the checkout and the script in an optional profile. This would also make the Maven build independent of SVN/Mercurial (https://github.com/daisy/pipeline-mod-braille/issues/28).

**Comment by dkager** [comment]
I second this. I’ll look at it.

**Comment by dkager** [comment]
In 83c3f20. There are still failing tests mucking things up on Windows, but it's a step forward.

**Comment by bertfrees** [comment]
Some comments:
- The profile should only work when activated explicitely with `-Pcheckout-tables`. Not sure if that's the case now.
- The generated files should be checked into git. I will take care of that. The README should also explain how to do this.
- Your XML editor messed up the indentation of the bash script so I suggest we move it to an external file to avoid that.

**Comment by bertfrees** [comment]
Also (detail) the liblouis-mathml doesn't need to be activated because there were no real code changes (except for those warnings you fixed).

**Comment by dkager** [comment]
Are you saying instead of activating on Unix the profile should be completely manual? In that case just remove the <os/> section. I’m still not sure why we don’t just put the tables in main/resources.

(There was a code change: I removed an unused variable. Oh ho ho!)

**Comment by dkager** [comment]
OK, reopening. I will fix this either today or next week. It's a good way to get to know Maven.

**Comment by bertfrees** [comment]
> I’m still not sure why we don’t just put the tables in main/resources.

Yes that's exactly the plan. I'm going to take care of that. In addition I want to keep the script because it makes moving to a newer version easier.

> (There was a code change: I removed an unused variable. Oh ho ho!)

I know... I mean if a module isn't going to be included in the next release it's preferable to have it deactivated so it's not build for no reason. Never mind, not a big deal.

**Comment by dkager** [comment]
If you keep the script, let's add it in an optional profile as you said, and maybe use [this](http://www.mojohaus.org/exec-maven-plugin/exec-mojo.html). I tried this locally and while the script obviously doesn't run on Windows the plugin seems to be a lot easier to understand.

**Comment by bertfrees** [comment]
Fixed by 4cb07d5dd2a35fc0d0da345ad2617168ae30f6ef
