### ISSUE TITLE
Implement generic mechanism for pre-processing XSLTs

### ISSUE THREAD

**Issue by josteinaj** [snaekobbi/pipeline-mod-braille#63]
> [15:02] &lt;frees&gt; i've been thinking about a more general step called px:apply-stylesheets
> [15:02] &lt;frees&gt; more general then css:inline

**Comment by bertfrees** [comment]
@josteinaj: this is ready to use now.

**Comment by bertfrees** [comment]
(typo)

**Comment by josteinaj** [comment]
Looks great, cool!
